name: GriefPreventionSendBlocks
version: "${version}"
main: de.jonas.griefpreventionsendblocks.GriefPreventionSendBlocks
api-version: "1.21"
authors:
  - Jon1Games
loader: de.jonas.griefpreventionsendblocks.GriefPreventionSendBlocksLoader
dependencies:
  server:
    GriefPrevention:
      load: BEFORE
      required: true
      join-classpath: true
